bproject/bproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
    path('freeBoard/',include('freeBoard.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bproject/freeBoard/urls.py
from django.urls import path,include
from . import views

app_name="freeBoard"
urlpatterns = [
    path('<int:nowpage>/<str:category>/<str:sword>/fboardList',views.fboardList,name="fboardList"),
    path('<int:nowpage>/<str:category>/<str:sword>/fboardWrite',views.fboardWrite,name="fboardWrite"),
    path('<int:nowpage>/<str:category>/<str:sword>/<str:b_no>/fboardView',views.fboardView,name="fboardView"),
    path('<int:nowpage>/<str:category>/<str:sword>/<str:b_no>/fboardUpdate',views.fboardUpdate,name="fboardUpdate"),
    path('<int:nowpage>/<str:category>/<str:sword>/<str:b_no>/fboardDelete',views.fboardDelete,name="fboardDelete"),
    path('<int:nowpage>/<str:category>/<str:sword>/<str:b_no>/fboardReply',views.fboardReply,name="fboardReply"),
    # event
    path('event/',views.event,name="event"),
    path('<str:b_no>/eventView/',views.eventView,name="eventView"),
    # ajax event
    path('commList/',views.commList,name="commList"),
    path('commWrite/',views.commWrite,name="commWrite"),
    path('commUpdate/',views.commUpdate,name="commUpdate"),
    path('commDelete/',views.commDelete,name="commDelete"),
    path('commPost/',views.commPost,name="commPost"),
    
    # 공공데이터
    path('publicList/',views.publicList,name="publicList"),
    path('chart01/',views.chart01,name="chart01"),
    path('chartData/',views.chartData,name="chartData"),
    path('chartList/',views.chartList,name="chartList"),
]

bproject/home/urls.py
from django.urls import path,include
from . import views

app_name = ''

urlpatterns = [
    path('', views.index, name='index')
]

bproject/member/urls.py
from django.urls import path,include
from . import views

app_name = 'member'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join01/',views.join01, name='join01'),
    path('join02/',views.join02, name='join02'),
    path('join03/',views.join03, name='join03'),
]

bproject/freeBoard/models.py
from datetime import datetime
from django.db import models
from member.models import Member

class Fboard(models.Model):
    b_no = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    b_title = models.CharField(max_length=1000)
    b_content = models.TextField()
    b_date = models.DateTimeField(default=datetime.now(),blank=True)
    b_group = models.IntegerField(default=0)
    b_step = models.IntegerField(default=0)
    b_indent = models.IntegerField(default=0)
    b_hit = models.IntegerField(default=1)
    b_file = models.ImageField(blank=True)
    
    def __str__(self):
        return self.b_title

class Comment(models.Model):    
    c_no = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING)
    fboard = models.ForeignKey(Fboard,on_delete=models.CASCADE)
    c_pw = models.CharField(max_length=10,blank=True)
    c_content = models.TextField()
    c_date = models.DateTimeField(default=datetime.now(),blank=True)
    
    def __str__(self):
        return self.c_content
    
class Revenue(models.Model):    
    r_no = models.AutoField(primary_key=True)
    r_month = models.CharField(max_length=10)
    r_revenue = models.IntegerField(default=0)
    
    def __str__(self):
        return self.r_month

bproject/freeBoard/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from freeBoard.models import Revenue
from member.models import Member
from freeBoard.models import Comment, Fboard
from django.db.models import F,Q
from django.core.paginator import Paginator
from django.http import JsonResponse,HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt
import requests

def chart01(request):
    return render(request, 'chart01.html')

@csrf_exempt
def chartData(request):
    qs = Revenue.objects.all()
    chartList = list(qs.values())
    return JsonResponse(chartList, safe=False)

@csrf_exempt
def chartList(request):
    public_key ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    resultType ='json'
    url = 'http://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo?serviceKey={}&numOfRows=10&pageNo=1&resultType={}'.format(public_key,resultType)
    res = requests.get(url)
    json_res = json.loads(res.text)
    publicList = json_res['response']['body']['items']['item']
    nlist = [1,2,3,4,5]
    
    return JsonResponse(publicList, safe=False)

# 공공데이터 리스트
def publicList(request):
    public_key ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    resultType ='json'
    url = 'http://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo?serviceKey={}&numOfRows=10&pageNo=1&resultType={}'.format(public_key,resultType)
    res = requests.get(url)
    json_res = json.loads(res.text)
    publicList = json_res['response']['body']['items']['item']
    numOfRows = json_res['response']['body']['numOfRows']
    context={'publicList':publicList,"numOfRows":numOfRows}
    
    return render(request,'publicList.html',context)

@csrf_exempt
def commPost(request):
    test = request.POST.get("test")
    context = {"msg":"데이터전송이 잘되었습니다." }
    return JsonResponse(context)


def commDelete(request):
    c_no = request.GET.get('c_no')
    qs = Comment.objects.get(c_no=c_no)
    qs.delete()
    context={'msg':"댓글이 삭제되었습니다."}
    return JsonResponse(context)

def commUpdate(request):
    c_no = request.GET.get('c_no')
    c_content = request.GET.get('c_content')
    id = request.session.get('session_id')
    qs = Comment.objects.get(c_no=c_no)
    qs.c_content = c_content
    qs.c_date = datetime.now()
    qs.save()
    
    context={"c_no":c_no,"c_content":c_content,"c_date":qs.c_date}
    return JsonResponse(context)
    
def commWrite(request):
    id = request.session.get('session_id')
    member = Member.objects.get(id=id)
    b_no = request.GET.get('b_no')
    fboard = Fboard.objects.get(b_no=b_no)
    c_pw = request.GET.get('c_pw')
    c_content = request.GET.get('c_content')
    
    qs = Comment(member=member,fboard=fboard,c_pw=c_pw,c_content = c_content)
    qs.save()
    c_no = qs.c_no
    c_date = qs.c_date
    
    context={"c_no":c_no,"b_no":b_no,"c_pw":c_pw,"c_content":c_content,"c_date":c_date}
    return JsonResponse(context) 
    
def commList(request):
    b_no = request.GET.get('b_no')
    comm_qs = Comment.objects.filter(fboard=b_no).order_by('-c_no')
    clist = list(comm_qs.values())
    
    return JsonResponse(clist,safe=False)
    
def event(request):
    qs = Fboard.objects.order_by('-b_group','b_step')  
    
    paginator = Paginator(qs,3)  
    qs = paginator.get_page(1)  
    
    context={"fboardList":qs}
    return render(request,'event.html',context)

def eventView(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_hit += 1  
    qs.save()
    comm_qs = Comment.objects.filter(fboard=b_no).order_by('-c_no')
    count = comm_qs.count()
    context = {"fboard":qs,"commList":comm_qs,"commCount":count}
    return render(request,'eventView.html',context)

def fboardReply(request,nowpage,category,sword,b_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(b_no=b_no)
        context = {"fboard":qs,"nowpage":nowpage,"category":category,"sword":sword}
        return render(request,'fboardReply.html',context)
    else:
        id = request.session['session_id'] 
        member = Member.objects.get(id=id)
        b_no = request.POST.get("no")
        b_group = int(request.POST.get("group"))  
        b_step = int(request.POST.get("step"))    
        b_indent = int(request.POST.get("indent")) 
        
        b_title = request.POST.get("title")
        b_content = request.POST.get("content")
        b_file = request.FILES.get('file',None)
        
        Fboard.objects.filter(b_group=b_group,b_step__gt=b_step).update\
            (b_step=F('b_step')+1)
        
        qs = Fboard(member=member,b_title=b_title,b_content=b_content,\
            b_group=b_group,b_step=b_step+1,b_indent=b_indent+1,b_file=b_file)
        qs.save()
        return redirect('freeBoard:fboardList', nowpage,category,sword)

def fboardDelete(request,nowpage,category,sword,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.delete()
    return redirect('freeBoard:fboardList', nowpage,category,sword)


def fboardUpdate(request,nowpage,category,sword,b_no):
    if request.method=='GET':
        qs = Fboard.objects.get(b_no=b_no)
        context = {"fboard":qs,"nowpage":nowpage,"category":category,"sword":sword}
        return render(request,'fboardUpdate.html',context)
    else:
        b_title = request.POST.get('title')
        b_content = request.POST.get('content')
        b_file = request.FILES.get('file',None)
        re_file = request.POST.get('refile')
        qs = Fboard.objects.get(b_no=b_no)
        qs.b_title = b_title
        qs.b_content = b_content
        qs.b_date = datetime.now()
        if b_file:
            qs.b_file=b_file
        qs.save()
        
        return redirect('freeBoard:fboardList', nowpage,category,sword)
        
def fboardView(request,nowpage,category,sword,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_hit += 1  
    qs.save()
    
    try:
        qs_prev = Fboard.objects.filter(b_group=qs.b_group,b_step__lt=qs.b_step).order_by('-b_group','b_step').last().b_no
    except:
        try:
            qs_prev = Fboard.objects.filter(b_group__gt=qs.b_group).order_by('-b_group','b_step').last().b_no
        except:
            qs_prev = Fboard.objects.order_by('-b_group','b_step').first().b_no
    try:
        qs_next = Fboard.objects.filter(b_group=qs.b_group,b_step__gt=qs.b_step).order_by('-b_group','b_step').first().b_no
    except:
        try:
            qs_next = Fboard.objects.filter(b_group__lt=qs.b_group).order_by('-b_group','b_step').first().b_no
        except:
            qs_next = Fboard.objects.order_by('-b_group','b_step').last().b_no    
    
    qsPrevData = Fboard.objects.get(b_no=qs_prev)
    qsNextData = Fboard.objects.get(b_no=qs_next)
    
    context = {"fboard":qs,'fboardPrev':qsPrevData,'fboardNext':qsNextData,'nowpage':nowpage,"category":category,"sword":sword}
    return render(request,'fboardView.html',context)

def fboardList(request,nowpage,category,sword):
    if request.method == "POST":
       ncategory = request.POST.get('category') 
       nsword = request.POST.get('sword')    
       category = ncategory
       sword = nsword
    if category=='1' and sword =='1':
        qs = Fboard.objects.order_by('-b_group','b_step')
    else:
        if category=='all':
            qs = Fboard.objects.filter(Q(b_title__contains=sword)|Q(b_content__contains=sword))
        elif category == 'title':
            qs = Fboard.objects.filter(b_title__contains=sword)
        else:
            qs = Fboard.objects.filter(b_content__contains=sword)    
    paginator = Paginator(qs,10) 
    qs = paginator.get_page(nowpage) 
    
    context={"fboardList":qs,"category":category,"sword":sword,"nowpage":nowpage}
    return render(request,'fboardList.html',context)     

def fboardWrite(request,nowpage,category,sword,):
    if request.method == 'GET':
        context={"nowpage":nowpage,"category":category,"sword":sword}
        return render(request,'fboardWrite.html',context)
    else:
        id = request.session['session_id']
        member = Member.objects.get(id=id)
        b_title = request.POST.get("title")
        b_content = request.POST.get("content")
        b_file = request.FILES.get('file',None)
        
        qs = Fboard(member=member,b_title=b_title,b_content=b_content,b_file=b_file)
        qs.save()
        qs.b_group = qs.b_no
        qs.save()
        return redirect('freeBoard:fboardList', nowpage,category,sword)

bproject/freeBoard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function writeBtn(){
      location.href="{% url 'freeBoard:fboardWrite' nowpage category sword %}"
    }

    function searchBtn(){
      if ($("#sword").val().length<=1){
        alert("두글자 이상 입력하셔야 합니다.")
        $("#sword").focus()
        return false
      }
      document.search.submit()
    }
  </script>
</head>
<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <a href="/"><div class="logo"></div></a>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>리뷰게시판</h1>
    <div class="wrapper">
      <form action="{% url 'freeBoard:fboardList' nowpage category sword %}" name="search" method="post">
        {% csrf_token %}
        <select name="category" id="category" >
          <option value="all" {% if 'all' in category %}selected {% endif %}>전체</option>
          <option value="title" {% if 'title' in category %}selected {% endif %}>제목</option>
          <option value="content" {% if 'content' in category %}selected {% endif %}>내용</option>
        </select>

        <div class="title">
          {% if '1' in category %}
            <input type="text" size="16" name="sword" id="sword" value="">
          {% else %}
            <input type="text" size="16" name="sword" id="sword" value="{{sword}}">
          {% endif %}
        </div>
        <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="45%">
        <col width="15%">
        <col width="15%">
        <col width="10%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      <!-- 반복 시작 -->
      {% for fboard in fboardList %}
      <tr>
        <td>{{fboard.b_no}}</td>
        <td class="table-title">
          {% comment %} <a href="freeBoard/fboardView?nowpage={{nowpage}}&b_no={{fboard.b_no}}"> {% endcomment %}
          <a href="{% url 'freeBoard:fboardView' nowpage category sword fboard.b_no %}">
            {% if fboard.b_indent > 0 %}
              {% comment %} rjust:공백제거후 fboard.b_indent만큼 리스트처리해줌 {% endcomment %}
              {% for i in "x"|rjust:fboard.b_indent %}
                ▶ 
              {% endfor %}
            {% endif %}
            {{fboard.b_title}}
          </a>
        </td>
        <td>{{fboard.member.name}}</td>
        <td>{{fboard.b_date|date:'Y-m-d H:i'}}</td>
        <td>{{fboard.b_hit}}</td>
      </tr>
      {% endfor %}
      <!-- 반복 끝 -->
    </table>

    <ul class="page-num">
      {% if fboardList.has_previous %}
        <a href="{% url 'freeBoard:fboardList' 1 category sword %}"><li class="first"></li></a>
        <a href="{% url 'freeBoard:fboardList' fboardList.previous_page_number category sword %}"><li class="prev"></li></a>
      {% else %}
        <li class="first"></li>
        <li class="prev"></li>
      {% endif %}
      <!-- 페이지처리 -->
      {% for page in fboardList.paginator.page_range %}
        {% if page == nowpage %}
          <li class="num numOver"><div>{{page}}</div></li>
        {% else %}
            <li class="num">
              <a href="{% url 'freeBoard:fboardList' page category sword %}"><div>{{page}}</div></a>
            </li>
        {% endif %}
      {% endfor %}
      <!--  페이지처리 끝 -->
      {% if fboardList.has_next %}
        <a href="{% url 'freeBoard:fboardList' fboardList.next_page_number category sword %}"><li class="next"></li></a>
        <a href="{% url 'freeBoard:fboardList' fboardList.paginator.num_pages category sword %}"><li class="last"></li></a>
      {% else %}
      <li class="next"></li>
      <li class="last"></li>
      {% endif %}
      
    </ul>

    <div class="write" onclick="writeBtn()">쓰기</div>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

bproject/freeBoard/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pages - Login</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
    function updateBtn(){
      if ($("#title").val()==""){
        alert("제목을 입력하셔야 등록이 가능합니다.")
        $("#title").focus()
        return false
      }
      document.write.submit()
    }

    function cancelBtn(){
      location.href="{% url 'freeBoard:fboardView' nowpage category sword fboard.b_no %}"
    }
  </script>
</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>게시판 수정</h1>
    <hr>

    <form action="{% url 'freeBoard:fboardUpdate' nowpage category sword fboard.b_no %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title" value={{fboard.b_title}}>
          </td>
        </tr>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id" value="{{request.session.session_id }}" readonly >
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10">{{fboard.b_content}}</textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
        <tr>
          <th>파일이름</th>
          {% if fboard.b_file %}
            <td>{{fboard.b_file}}</td>
            <input type="hidden" name="refile" value="{{fboard.b_file}}">
          {% else %}
            <td>데이터 없음</td>
          {% endif %}
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" onclick="updateBtn()" class="write">수정</button>
        <button type="button" onclick="cancelBtn()" class="cancel">취소</button>
      </div>
    </form>

  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

bproject/freeBoard/templates/fboardView.html
{% extends './base.html' %}
{% load static %}
{% block content-block %}
    {% if not request.session.session_id %}
     <script>
        alert('로그인을 하셔야 접근이 가능합니다.')
        location.href = "{% url 'member:login' %}"
     </script>
  {% endif %}
  <script>
    function delBtn(){
      if(confirm("정말 삭제하시겠습니까?")){
        location.href="{% url 'freeBoard:fboardDelete' nowpage category sword fboard.b_no %}"
      }
    }
  </script>
    <h1>리뷰게시판</h1>

    <table>
      <tr>
        <th><strong>제목</strong><span class="separator">|</span>{{fboard.b_title}}</th>
      </tr>
      <tr>
        <td><strong>작성자</strong><span class="separator">|</span>{{fboard.member.name}}</td>
      </tr>
      <tr>
        <td><strong>날짜</strong><span class="separator">|</span>{{fboard.b_date|date:'Y-m-d H:i'}}</td>
      </tr>
      <tr>
        <td><strong>내용</strong><span class="separator">|</span>{{fboard.b_content | safe }}</td>
      </tr>
      <tr>
        <td class="article">
          <img src="/media/{{fboard.b_file}}" alt="" width="80%">
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span>
          <a href="{% url 'freeBoard:fboardView' nowpage category sword fboardNext.b_no  %}">{{fboardNext.b_title}}</a>
        </td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span>
          <a href="{% url 'freeBoard:fboardView' nowpage category sword fboardPrev.b_no  %}">{{fboardPrev.b_title}}</a>
        </td>
      </tr>
    </table>

    <a href="{% url 'freeBoard:fboardList' nowpage category sword %}"><div class="list" >목록</div></a>
    <div class="list" onclick="delBtn()">삭제</div>
    <a href="{% url 'freeBoard:fboardUpdate' nowpage category sword fboard.b_no %}"><div class="list">수정</div></a>
    <a href="{% url 'freeBoard:fboardReply' nowpage category sword fboard.b_no %}"><div class="list">답글쓰기</div></a>
  {% endblock content-block %}